language: python
python: "2.7"
install: pip install -r requirements.txt
script: nosetests
deploy:
  provider: gae
  project: cmoanderic
  version: master-0x2x4
  on: master
  no_promote: true
before_install:
- openssl aes-256-cbc -K $encrypted_90ad7d4287bd_key -iv $encrypted_90ad7d4287bd_iv
  -in service-account.json.enc -out service-account.json -d
